servers:
  web:
    hosts:
      - church-needs
    options:
      memory: 512m
      memory-swap: 512m
      cpus: 1

# Enable zero-downtime deployments by keeping old containers until new ones are healthy
retain_containers: 2

proxy:
  ssl: true
  host: churchneeds.net
  app_port: 80
  forward_headers: true
  healthcheck:
    path: /up
    interval: 10
    timeout: 30

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTMARK_API_TOKEN
    - POSTMARK_WEBHOOK_USERNAME
    - POSTMARK_WEBHOOK_PASSWORD
    - STRIPE_SECRET_KEY
    - STRIPE_PUBLISHABLE_KEY
    - STRIPE_WEBHOOK_SECRET
    - TELNYX_API_KEY
    - TELNYX_MESSAGING_PROFILE_ID
    - TELNYX_PHONE_NUMBER
  clear:
    # Set the host for URL generation (production environment)
    APP_HOST: churchneeds.net

    # Don't use database prefix in production (override staging config)
    DATABASE_PREFIX: ""

    # Optimized Puma configuration for 512MB web container
    # WEB_CONCURRENCY: 1 means 1 master + 1 worker = 2 processes (lower memory)
    WEB_CONCURRENCY: 1
    RAILS_MAX_THREADS: 5

    # Disable Solid Queue in Puma - causes boot hang on recent deployments
    SOLID_QUEUE_IN_PUMA: "false"

    # Skip db:prepare to prevent OOM during deployment
    SKIP_DB_PREPARE: "true"

    # Ruby memory management for 512MB container
    MALLOC_ARENA_MAX: 2
    RUBY_GC_HEAP_GROWTH_FACTOR: 1.1
    RUBY_GC_HEAP_GROWTH_MAX_SLOTS: 10000
    RUBY_GC_MALLOC_LIMIT: 16777216

# Use a different ssh user than root
ssh:
  user: needs

# Dedicated Solid Queue for production background jobs
accessories:
  solid_queue:
    image: registry.digitalocean.com/roaringlambproductions/needs:latest-production
    host: church-needs
    cmd: bundle exec rake solid_queue:start
    volumes:
      - "needs_storage:/rails/storage"
    env:
      clear:
        RAILS_ENV: production
        # Don't use database prefix in production
        DATABASE_PREFIX: ""
        # Minimal Solid Queue configuration for low-usage production (192MB container)
        # These map to config/solid_queue.yml settings:
        # - SOLID_QUEUE_PROCESSES: number of worker processes (default 1)
        # - SOLID_QUEUE_CONCURRENCY: threads per process (default 1)
        # - SOLID_QUEUE_POLL_INTERVAL: polling frequency in seconds (default 2)
        SOLID_QUEUE_POLL_INTERVAL: 5
        SOLID_QUEUE_CONCURRENCY: 1
        SOLID_QUEUE_PROCESSES: 1
      secret:
        - RAILS_MASTER_KEY
        - POSTMARK_API_TOKEN
        - STRIPE_SECRET_KEY
        - TELNYX_API_KEY
        - TELNYX_MESSAGING_PROFILE_ID
        - TELNYX_PHONE_NUMBER
    options:
      memory: 192m
      memory-swap: 192m
      cpus: 0.5
