servers:
  web:
    hosts:
      - church-needs
    options:
      memory: 350m
      memory-swap: 350m
      cpus: 1

proxy:
  ssl: true
  host: churchneeds.net
  app_port: 80
  forward_headers: true
  healthcheck:
    path: /up
    interval: 10
    timeout: 30

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTMARK_API_TOKEN
    - POSTMARK_WEBHOOK_USERNAME
    - POSTMARK_WEBHOOK_PASSWORD
    - STRIPE_SECRET_KEY
    - STRIPE_PUBLISHABLE_KEY
    - STRIPE_WEBHOOK_SECRET
    - TELNYX_API_KEY
    - TELNYX_MESSAGING_PROFILE_ID
    - TELNYX_PHONE_NUMBER
  clear:
    # Set the host for URL generation (production environment)
    APP_HOST: churchneeds.net

    # Don't use database prefix in production (override staging config)
    DATABASE_PREFIX: ""

    # Reduced Puma configuration for memory-constrained server
    # WEB_CONCURRENCY: 2 means 1 master + 2 workers = 3 processes
    WEB_CONCURRENCY: 2
    RAILS_MAX_THREADS: 5

    # Disable Solid Queue in Puma - causes boot hang on recent deployments
    SOLID_QUEUE_IN_PUMA: "false"

    # Skip db:prepare to prevent OOM during deployment
    SKIP_DB_PREPARE: "true"

# Use a different ssh user than root
ssh:
  user: needs

# Dedicated Solid Queue for production background jobs
accessories:
  solid_queue:
    image: roaringlambproductions/needs:latest-production
    host: church-needs
    cmd: bundle exec rake solid_queue:start
    volumes:
      - "needs_storage:/rails/storage"
    env:
      clear:
        RAILS_ENV: production
        # Don't use database prefix in production
        DATABASE_PREFIX: ""
        # Reduced concurrency for memory-constrained server
        SOLID_QUEUE_POLL_INTERVAL: 2
        SOLID_QUEUE_CONCURRENCY: 2
        SOLID_QUEUE_PROCESSES: 2
        SOLID_QUEUE_DISPATCHERS: 1
        SOLID_QUEUE_WORKERS: 2
      secret:
        - RAILS_MASTER_KEY
        - POSTMARK_API_TOKEN
        - STRIPE_SECRET_KEY
        - TELNYX_API_KEY
        - TELNYX_MESSAGING_PROFILE_ID
        - TELNYX_PHONE_NUMBER
    options:
      memory: 256m
      memory-swap: 256m
      cpus: 0.5
