servers:
  web:
    hosts:
      - church-needs
    options:
      memory: 1gb
      memory-swap: 1gb
      cpus: 1

proxy:
  ssl: true
  host: churchneeds.net
  app_port: 80
  forward_headers: true
  healthcheck:
    path: /up
    interval: 10
    timeout: 30

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTMARK_API_TOKEN
    - POSTMARK_WEBHOOK_USERNAME
    - POSTMARK_WEBHOOK_PASSWORD
    - STRIPE_SECRET_KEY
    - STRIPE_PUBLISHABLE_KEY
    - STRIPE_WEBHOOK_SECRET
    - TELNYX_API_KEY
    - TELNYX_MESSAGING_PROFILE_ID
    - TELNYX_PHONE_NUMBER
  clear:
    # Set the host for URL generation (production environment)
    APP_HOST: churchneeds.net

    # Standard production Puma configuration for 1GB RAM
    WEB_CONCURRENCY: 2
    RAILS_MAX_THREADS: 5

    # Disable Solid Queue in Puma - causes boot hang on recent deployments
    SOLID_QUEUE_IN_PUMA: "false"
    
    # Skip db:prepare to prevent OOM during deployment
    SKIP_DB_PREPARE: "true"

# Use a different ssh user than root
ssh:
  user: needs

