servers:
  web:
    hosts:
      - church-needs
    options:
      memory: 750m
      memory-swap: 750m
      cpus: 1

proxy:
  ssl: true
  host: churchneeds.net
  app_port: 80
  forward_headers: true
  healthcheck:
    path: /up
    interval: 10
    timeout: 20

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTMARK_API_TOKEN
  clear:
    # Standard production Puma configuration for 1GB RAM
    WEB_CONCURRENCY: 2
    RAILS_MAX_THREADS: 5

    # Run Solid Queue inside Puma for single-server setup
    SOLID_QUEUE_IN_PUMA: true

# Use a different ssh user than root
ssh:
  user: needs

